[package]
name = "targ"
version = "0.1.0"
edition = "2021"

[dependencies]
ratatui = "0.30"
crossterm = "0.29"
tar = "0.4"
flate2 = "1.0"
chrono = "0.4"
clap = { version = "4", features = ["derive", "cargo"] }
